#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""mkldr.py -- turn an SCV1 OS image into a loader script.

A .ldr file is a plain text list of APDUs, one per line, hex, with '#'
comments. That is the same shape as the loader transcripts a real card
programmer produces, and it is directly consumable by the SCV1 transport --
both the QEMU firmware and the native simulator skip comment lines.

    tools/mkldr.py os build-arm/smartcard-os.bin -o os.ldr
    tools/mkldr.py recycle -o recycle.ldr
    tools/mkldr.py inspect os.ldr
    tools/mkldr.py slot build-arm/smartcard-os.bin -d mycard

THE PROTOCOL EMITTED HERE IS OURS. It is documented in
include/boot/boot_loader.h and docs/chip-scv1.md, and it is NOT any vendor's
loader protocol. Nothing here was derived from a captured trace of a real
card.

os.ldr contains, in order:

    ERASE               wipe the OS slot to 0xFF
    LOAD BLOCK * N      the image, 128 bytes at a time
    VERIFY              declare the length and CRC; the card checks both and
                        writes the slot header
    ACTIVATE            mark the slot bootable
    RESTART             hand the core to the freshly loaded OS

ERASE comes first inside os.ldr as well as in recycle.ldr, because loading
over an unerased slot is refused -- flash cannot set a bit back to 1.
"""

import argparse
import sys

BLOCK = 128


def crc16(data: bytes) -> int:
    """CRC-16/CCITT-FALSE. Must agree with src/kernel/crc16.c byte for byte.

    Poly 0x1021, init 0xFFFF, no reflection, no final xor.
    Known answer: crc16(b"123456789") == 0x29B1.
    """
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if (crc & 0x8000) else (crc << 1) & 0xFFFF
    return crc


def apdu(cla, ins, p1, p2, data=b"") -> str:
    if data:
        return f"{cla:02X}{ins:02X}{p1:02X}{p2:02X}{len(data):02X}" + data.hex().upper()
    return f"{cla:02X}{ins:02X}{p1:02X}{p2:02X}00"


def cmd_erase() -> str:
    return apdu(0x80, 0x0E, 0, 0)


def gen_recycle() -> list:
    return [
        "# recycle.ldr -- return an SCV1 to the state it left the factory in.",
        "#",
        "# Erases the OS slot and its header. Afterwards the card answers with",
        "# the BOOT ROM's ATR (3B 94 11 00 42 4F 4F 54) rather than the OS's,",
        "# because the boot loader is what is answering.",
        "#",
        "# This does NOT touch EEPROM or DFLASH -- the filesystem survives. A",
        "# real product would wipe those too at recycle time; doing it here",
        "# needs a command the OS owns, not one the boot loader owns.",
        "",
        "# GET STATUS -- so a transcript shows what was there before",
        apdu(0x80, 0xF2, 0, 0),
        "",
        "# ERASE",
        cmd_erase(),
        "",
        "# GET STATUS -- should now report slot state 00 (BLANK)",
        apdu(0x80, 0xF2, 0, 0),
    ]


def gen_os(image: bytes, restart: bool) -> list:
    n = len(image)
    crc = crc16(image)
    nblocks = (n + BLOCK - 1) // BLOCK

    out = [
        "# os.ldr -- load a SmartCard OS image into an SCV1 OS slot.",
        "#",
        f"# image length : {n} bytes",
        f"# CRC-16       : {crc:04X}  (CCITT-FALSE, poly 1021, init FFFF)",
        f"# blocks       : {nblocks} x {BLOCK} bytes",
        f"# load address : 0x00002000  (OSFLASH)",
        "#",
        "# Generated by tools/mkldr.py. Protocol: include/boot/boot_loader.h",
        "",
        "# --- ERASE ----------------------------------------------------------",
        cmd_erase(),
        "",
        "# --- LOAD BLOCK -----------------------------------------------------",
        "# 80 54 <block hi> <block lo> <len> <data>   offset = block * 128",
    ]

    for i in range(nblocks):
        chunk = image[i * BLOCK:(i + 1) * BLOCK]
        out.append(apdu(0x80, 0x54, (i >> 8) & 0xFF, i & 0xFF, chunk))

    body = n.to_bytes(4, "big") + crc.to_bytes(2, "big")
    out += [
        "",
        "# --- VERIFY ---------------------------------------------------------",
        "# 80 A0 00 00 06 <length:4> <crc:2>",
        "# The card recomputes the CRC over what it actually stored, checks the",
        "# image's first two words look like an ARMv7-M vector table, and only",
        "# then writes the slot header. A failure here leaves no header behind.",
        apdu(0x80, 0xA0, 0, 0, body),
        "",
        "# --- ACTIVATE -------------------------------------------------------",
        "# Separate from VERIFY on purpose: a card that was powered off midway",
        "# through a load must not come up running a partial OS.",
        apdu(0x80, 0x44, 0, 0),
        "",
        "# --- GET STATUS -----------------------------------------------------",
        "# Expect: 01 02 <capacity:4> <length:4> <crc:2> 80 01 <hw:2> 9000",
        "#             ^^ slot state 02 = ACTIVE",
        apdu(0x80, 0xF2, 0, 0),
    ]
    if restart:
        out += [
            "",
            "# --- RESTART --------------------------------------------------------",
            "# Hands the core to the loaded OS. Everything after this line is",
            "# answered by the OS, not by the boot loader -- including the ATR.",
            apdu(0x80, 0xF0, 0, 0),
        ]
    return out


def cmd_slot(image: bytes, out_dir: str, active: bool) -> int:
    """Write a pre-programmed OS slot directly, bypassing the APDU loader.

    This is the gang-programmer path: at the factory nobody sends 106 APDUs per
    card, they write the flash image straight in before the part is packaged.
    It produces exactly what the loader would have produced -- same slot header
    layout, same CRC -- so the boot ROM cannot tell the two apart, which is the
    property worth having.

    Used by the integration test suite so that testing the OS over QEMU does
    not mean replaying a loader script on every single test case.
    """
    import os as _os

    cap = 55 * 1024
    if len(image) > cap:
        print(f"mkldr: image is {len(image)} bytes, slot holds {cap}", file=sys.stderr)
        return 1

    osflash = image + b"\xFF" * (cap - len(image))

    hdr = bytearray(b"\xFF" * 1024)
    hdr[0:4]   = b"SCOS"
    hdr[4:6]   = (1).to_bytes(2, "big")
    hdr[6:10]  = len(image).to_bytes(4, "big")
    hdr[10:12] = crc16(image).to_bytes(2, "big")
    hdr[12:14] = crc16(bytes(hdr[0:12])).to_bytes(2, "big")
    # State: all bits clear = ACTIVE, left erased = LOADED-but-not-bootable.
    hdr[14:16] = b"\x00\x00" if active else b"\xFF\xFF"

    _os.makedirs(out_dir, exist_ok=True)
    with open(_os.path.join(out_dir, "card_osflash.bin"), "wb") as f:
        f.write(osflash)
    with open(_os.path.join(out_dir, "card_oshdr.bin"), "wb") as f:
        f.write(bytes(hdr))
    print(f"wrote {out_dir}/card_osflash.bin ({cap} bytes) and card_oshdr.bin "
          f"(1024 bytes): {len(image)} byte image, CRC {crc16(image):04X}, "
          f"{'ACTIVE' if active else 'LOADED'}")
    return 0


def cmd_inspect(path: str) -> int:
    counts = {}
    total_data = 0
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("."):
                continue
            try:
                b = bytes.fromhex(line)
            except ValueError:
                print(f"not hex: {line[:40]}", file=sys.stderr)
                return 1
            if len(b) < 4:
                print(f"short APDU: {line}", file=sys.stderr)
                return 1
            name = {0xF2: "GET STATUS", 0x0E: "ERASE", 0x54: "LOAD BLOCK",
                    0xA0: "VERIFY", 0x44: "ACTIVATE", 0xF0: "RESTART"}.get(b[1], f"INS {b[1]:02X}")
            counts[name] = counts.get(name, 0) + 1
            if b[1] == 0x54 and len(b) > 5:
                total_data += b[4]
    for k, v in counts.items():
        print(f"{v:6d}  {k}")
    if total_data:
        print(f"{total_data:6d}  bytes of image data")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("os", help="build os.ldr from a raw OS image")
    p.add_argument("image", help="raw binary, e.g. build-arm/smartcard-os.bin")
    p.add_argument("-o", "--out", default="os.ldr")
    p.add_argument("--no-restart", action="store_true",
                   help="stop after ACTIVATE; the OS starts on the next reset")
    p.add_argument("--force", action="store_true",
                   help="emit the script even if the image does not look like "
                        "SCV1 firmware. The first command is ERASE, so this can "
                        "leave a working card blank.")

    p = sub.add_parser("recycle", help="build recycle.ldr")
    p.add_argument("-o", "--out", default="recycle.ldr")

    p = sub.add_parser("slot", help="write a pre-programmed slot (no APDUs)")
    p.add_argument("image", help="raw binary, e.g. build-arm/smartcard-os.bin")
    p.add_argument("-d", "--out-dir", required=True,
                   help="directory to write card_osflash.bin / card_oshdr.bin")
    p.add_argument("--loaded-only", action="store_true",
                   help="leave the slot LOADED rather than ACTIVE, so the boot "
                        "ROM stays in the loader")

    p = sub.add_parser("inspect", help="summarise a .ldr file")
    p.add_argument("path")

    args = ap.parse_args()

    if args.cmd == "inspect":
        return cmd_inspect(args.path)

    if args.cmd == "slot":
        with open(args.image, "rb") as f:
            return cmd_slot(f.read(), args.out_dir, active=not args.loaded_only)

    if args.cmd == "recycle":
        lines = gen_recycle()
    else:
        with open(args.image, "rb") as f:
            image = f.read()
        if len(image) < 8:
            print("mkldr: image is too short to contain a vector table", file=sys.stderr)
            return 1
        # Check the image BEFORE emitting a script that begins with ERASE.
        #
        # These were warnings once, and that was a real defect: tools/load-os.sh
        # ran anyway, the card erased its working OS, and only then did VERIFY
        # refuse the new image with 6984 -- leaving a blank card. The host knew
        # the image was bad and destroyed the card regardless. ERASE is
        # irreversible, so anything detectable up here has to stop us before we
        # get there.
        sp = int.from_bytes(image[0:4], "little")
        pc = int.from_bytes(image[4:8], "little")
        problems = []
        if not (0x20000000 < sp <= 0x20004000):
            problems.append(
                f"initial SP {sp:#010x} is not inside SCV1 SRAM "
                "(0x20000000..0x20004000)")
        if not (pc & 1):
            problems.append(
                f"reset vector {pc:#010x} has the Thumb bit clear; ARMv7-M has "
                "no ARM state, so this would fault immediately")
        elif not (0x00002000 <= (pc & ~1) < 0x00002000 + len(image)):
            problems.append(
                f"reset vector {pc:#010x} is outside the image; was it linked "
                "for 0x00002000? (see src/hal/arm-scv1/scv1.ld)")
        if problems and not args.force:
            print(f"mkldr: refusing to build a loader script for {args.image}:",
                  file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            print("\nThe card would erase its current OS and then reject this "
                  "image, leaving a blank\ncard. Pass --force if you really "
                  "mean it.", file=sys.stderr)
            return 1
        for p in problems:
            print(f"mkldr: WARNING (--force) {p}", file=sys.stderr)
        lines = gen_os(image, restart=not args.no_restart)

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
